workflows:
  android-debug-workflow:
    name: Android Debug (Final Cleanup)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        # لضمان عدم حدوث خطأ Java heap space مجدداً
        JAVA_OPTS: "-Xmx4G"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4G"
      flutter: stable
      java: 21 
    scripts:
      - name: Clean and Get packages
        script: |
          flutter clean
          flutter pub get
      - name: Build Android Debug APK
        script: |
          export GRADLE_OPTS="-Xmx4G"
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
